version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
    groups:
      tree-sitter:
        patterns:
          - "github.com/tree-sitter/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(actions)"
