package source

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDiscoverSupportedFilesAndDefaultExcludes(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, "main.go"), "package fixture\n")
	writeFixture(t, filepath.Join(root, "src", "check.py"), "def check():\n    return True\n")
	writeFixture(t, filepath.Join(root, "vendor", "ignored.go"), "package ignored\n")
	writeFixture(t, filepath.Join(root, "README.md"), "# ignored\n")

	result := Discover([]string{root}, Options{MaxFileBytes: 1024})
	if len(result.Warnings) != 0 {
		t.Fatalf("warnings = %#v, want none", result.Warnings)
	}
	if len(result.Files) != 2 {
		t.Fatalf("files = %d, want 2", len(result.Files))
	}
	if len(result.Unsupported) != 1 || result.Unsupported[0].Extension != ".md" ||
		result.Unsupported[0].FileCount != 1 {
		t.Fatalf("unsupported = %#v, want one .md file", result.Unsupported)
	}
	if !strings.HasSuffix(result.Files[0].DisplayPath, "main.go") {
		t.Fatalf("first file = %q, want main.go", result.Files[0].DisplayPath)
	}
	if !strings.HasSuffix(result.Files[1].DisplayPath, "src/check.py") {
		t.Fatalf("second file = %q, want src/check.py", result.Files[1].DisplayPath)
	}
}

func TestDiscoverSkipsLinkedWorktreeGitControlFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, ".git"), "gitdir: /tmp/example\n")
	writeFixture(t, filepath.Join(root, "README.md"), "# docs\n")
	result := Discover([]string{root}, Options{})
	if len(result.Files) != 0 || len(result.Warnings) != 0 ||
		len(result.Unsupported) != 1 || result.Unsupported[0].Extension != ".md" {
		t.Fatalf("result = %#v", result)
	}
}

func TestDiscoverExtensionlessScriptsByShebang(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	zsh := filepath.Join(root, "syncpick")
	bash := filepath.Join(root, "build")
	unsupported := filepath.Join(root, "fish-tool")
	writeFixture(t, zsh, "#!/bin/zsh\nrun() { print ok; }\n")
	writeFixture(t, bash, "#!/usr/bin/env -S bash -eu\nrun() { printf '%s\\n' ok; }\n")
	writeFixture(t, unsupported, "#!/usr/bin/env fish\nfunction run; echo ok; end\n")

	result := Discover([]string{root}, Options{MaxFileBytes: 1024})
	if len(result.Warnings) != 0 || len(result.Files) != 2 {
		t.Fatalf("result = %#v, want two supported scripts and no warnings", result)
	}
	if result.Files[0].Language.ID != "bash" || result.Files[1].Language.ID != "zsh" {
		t.Fatalf("languages = %s/%s, want bash/zsh", result.Files[0].Language.ID, result.Files[1].Language.ID)
	}

	explicit := Discover([]string{unsupported}, Options{})
	if len(explicit.Files) != 0 || len(explicit.Warnings) != 1 ||
		explicit.Warnings[0].Message != "unsupported source extension or shebang" {
		t.Fatalf("explicit unsupported script result = %#v", explicit)
	}
}

func TestDiscoverDoesNotUseShebangToOverrideExtension(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "script.py")
	writeFixture(t, path, "#!/bin/zsh\ndef run():\n    return True\n")
	result := Discover([]string{path}, Options{})
	if len(result.Files) != 1 || result.Files[0].Language.ID != "python" || len(result.Warnings) != 0 {
		t.Fatalf("result = %#v, want extension-selected Python", result)
	}
}

func TestDiscoverClassifiesAndOptionallyExcludesGeneratedFiles(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	generatedGo := filepath.Join(root, "generated.go")
	generatedTS := filepath.Join(root, "routeTree.gen.ts")
	generatedSwift := filepath.Join(root, "APITypes.swift")
	generatedSwiftProtobuf := filepath.Join(root, "model.pb.swift")
	handwritten := filepath.Join(root, "main.go")
	stringLiteral := filepath.Join(root, "literal.go")
	nonTypeshare := filepath.Join(root, "generator.swift")
	nonSwiftProtobuf := filepath.Join(root, "protobuf-helper.swift")
	writeFixture(t, generatedGo, "// Code generated by sqlc. DO NOT EDIT.\npackage fixture\n")
	writeFixture(t, generatedTS, "// This file was automatically generated by TanStack Router.\nexport function route() {}\n")
	writeFixture(t, generatedSwift, "/*\n Generated by typeshare 1.13.4\n */\nfunc decode() {}\n")
	writeFixture(t, generatedSwiftProtobuf, "// DO NOT EDIT.\n// swift-format-ignore-file\n// swiftlint:disable all\n//\n// Generated by the Swift generator plugin for the protocol buffer compiler.\n// Source: model.proto\nfunc decode() {}\n")
	writeFixture(t, handwritten, "package fixture\n")
	writeFixture(t, stringLiteral, "package fixture\nconst warning = \"Code generated; DO NOT EDIT\"\n")
	writeFixture(t, nonTypeshare, "// Generated by a project helper\nfunc build() {}\n")
	writeFixture(t, nonSwiftProtobuf, "// DO NOT EDIT.\n// Generated by the Swift build helper.\nfunc build() {}\n")

	included := Discover([]string{root}, Options{})
	if len(included.Files) != 8 || len(included.Excluded) != 0 {
		t.Fatalf("included result = %#v, want eight files", included)
	}
	generated := 0
	for _, file := range included.Files {
		if file.Generated {
			generated++
		}
	}
	if generated != 4 {
		t.Fatalf("generated files = %d, want 4: %#v", generated, included.Files)
	}

	excluded := Discover([]string{root}, Options{ExcludeGenerated: true})
	if len(excluded.Files) != 4 || len(excluded.Excluded) != 4 {
		t.Fatalf("excluded result = %#v, want four analyzed and four excluded", excluded)
	}
	markers := make(map[string]bool)
	for _, coverage := range excluded.Excluded {
		if coverage.Status != "excluded_generated" || !coverage.Generated || coverage.GeneratedMarker == "" ||
			coverage.ZeroReason != "generated_excluded" {
			t.Fatalf("excluded coverage = %#v", coverage)
		}
		markers[coverage.GeneratedMarker] = true
	}
	if !markers["typeshare-generated"] {
		t.Fatalf("generated markers = %#v, want Typeshare", markers)
	}
	if !markers["swift-protobuf-generated"] {
		t.Fatalf("generated markers = %#v, want SwiftProtobuf", markers)
	}
}

func TestDiscoverCustomExcludeAndExplicitWarning(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	included := filepath.Join(root, "main.go")
	excluded := filepath.Join(root, "main_test.go")
	unsupported := filepath.Join(root, "notes.md")
	writeFixture(t, included, "package fixture\n")
	writeFixture(t, excluded, "package fixture\n")
	writeFixture(t, unsupported, "# notes\n")

	result := Discover(
		[]string{root, unsupported},
		Options{Excludes: []string{"**/*_test.go"}},
	)
	if len(result.Files) != 1 || result.Files[0].Path != included {
		t.Fatalf("files = %#v, want only %q", result.Files, included)
	}
	if len(result.Warnings) != 1 ||
		result.Warnings[0].Message != "unsupported source extension" {
		t.Fatalf("warnings = %#v, want unsupported extension", result.Warnings)
	}
}

func TestDiscoverExcludesExplicitFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	excluded := filepath.Join(root, "main_test.go")
	writeFixture(t, excluded, "package fixture\n")

	result := Discover(
		[]string{excluded},
		Options{Excludes: []string{"**/*_test.go"}},
	)
	if len(result.Files) != 0 || len(result.Warnings) != 0 {
		t.Fatalf("result = %#v, want an excluded file with no warning", result)
	}
}

func TestDiscoverFiltersComparisonDomainsBeforeFileChecks(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	code := filepath.Join(root, "main.go")
	sql := filepath.Join(root, "schema.sql")
	writeFixture(t, code, "package fixture\n")
	writeFixture(t, sql, strings.Repeat("-", 2048))

	result := Discover([]string{root, sql}, Options{
		MaxFileBytes: 1024,
		ComparisonDomains: map[string]struct{}{
			"code": {},
		},
	})
	if len(result.Files) != 1 || result.Files[0].Path != code || len(result.Warnings) != 0 {
		t.Fatalf("domain-filtered result = %#v", result)
	}
}

func TestDiscoverInventoriesSupportedFilesSkippedByResourceLimit(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "large.go")
	writeFixture(t, path, "package fixture\nfunc Large() {}\n")
	result := Discover([]string{path}, Options{MaxFileBytes: 1})
	if len(result.Files) != 0 || len(result.Warnings) != 1 || len(result.Excluded) != 1 {
		t.Fatalf("result = %#v", result)
	}
	coverage := result.Excluded[0]
	if coverage.Language != "go" || coverage.Status != "skipped_resource" ||
		coverage.ZeroReason != "resource_limit" {
		t.Fatalf("coverage = %#v", coverage)
	}
}

func TestDiscoverIncludesOnlyGoHostsForOptInEmbeddedSQL(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	goPath := filepath.Join(root, "queries.go")
	tsPath := filepath.Join(root, "queries.ts")
	sqlPath := filepath.Join(root, "queries.sql")
	writeFixture(t, goPath, "package fixture\n")
	writeFixture(t, tsPath, "export function query() {}\n")
	writeFixture(t, sqlPath, "SELECT 1;\n")
	result := Discover([]string{root}, Options{
		ComparisonDomains: map[string]struct{}{"sql-query": {}}, EmbeddedSQL: true,
	})
	if len(result.Files) != 2 || result.Files[0].Path != goPath || result.Files[1].Path != sqlPath ||
		result.Files[0].AnalysisDomain != "sql-query" {
		t.Fatalf("embedded-SQL discovery = %#v", result)
	}
}

func TestDiscoverSelectsPostgreSQLDialect(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "migration.sql")
	writeFixture(t, path, "SELECT 1;\n")
	result := Discover([]string{path}, Options{SQLDialect: "postgresql"})
	if len(result.Files) != 1 || result.Files[0].Language.ID != "postgresql" ||
		len(result.Warnings) != 0 {
		t.Fatalf("PostgreSQL discovery = %#v", result)
	}
}

func TestDiscoverContextStopsBeforeWalking(t *testing.T) {
	t.Parallel()

	ctx, cancel := context.WithCancel(context.Background())
	cancel()
	_, err := DiscoverContext(ctx, []string{"."}, Options{})
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("DiscoverContext error = %v, want context.Canceled", err)
	}
}

func TestSymlinkComponentDetectionStopsAtBoundary(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	target := filepath.Join(root, "target")
	if err := os.Mkdir(target, 0o700); err != nil {
		t.Fatalf("Mkdir: %v", err)
	}
	writeFixture(t, filepath.Join(target, "source.go"), "package fixture\n")
	link := filepath.Join(root, "link")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("Symlink unavailable: %v", err)
	}
	hasSymlink, err := hasSymlinkComponent(filepath.Join(link, "source.go"), root)
	if err != nil {
		t.Fatalf("hasSymlinkComponent: %v", err)
	}
	if !hasSymlink {
		t.Fatal("hasSymlinkComponent = false, want true")
	}
}

func TestDiscoverRejectsSymlinkedAncestorOutsideWorkingDirectory(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	target := filepath.Join(root, "target")
	writeFixture(t, filepath.Join(target, "source.go"), "package fixture\n")
	link := filepath.Join(root, "link")
	if err := os.Symlink(target, link); err != nil {
		t.Skipf("Symlink unavailable: %v", err)
	}

	result := Discover([]string{filepath.Join(link, "source.go")}, Options{})
	if len(result.Files) != 0 || len(result.Warnings) != 1 {
		t.Fatalf("result = %#v, want no files and one warning", result)
	}
	if !strings.Contains(result.Warnings[0].Message, "symbolic links") {
		t.Fatalf("warning = %#v, want symbolic-link explanation", result.Warnings[0])
	}
}

func TestDiscoverWarningDoesNotRepeatAbsolutePath(t *testing.T) {
	t.Parallel()

	missing := filepath.Join(t.TempDir(), "missing.go")
	result := Discover([]string{missing}, Options{})
	if len(result.Warnings) != 1 {
		t.Fatalf("warnings = %#v, want one", result.Warnings)
	}
	if strings.Contains(result.Warnings[0].Message, missing) {
		t.Fatalf("warning message %q contains absolute path", result.Warnings[0].Message)
	}
}

func TestValidatePatterns(t *testing.T) {
	t.Parallel()

	if err := ValidatePatterns([]string{"**/*_test.go"}); err != nil {
		t.Fatalf("valid pattern: %v", err)
	}
	if err := ValidatePatterns([]string{"["}); err == nil {
		t.Fatal("invalid pattern returned nil")
	}
}

func TestDiscoverHonorsNestedGitAndMoriIgnoreRules(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, ".gitignore"), "generated/\n!generated/keep.go\n")
	writeFixture(t, filepath.Join(root, ".moriignore"), "private.go\n")
	writeFixture(t, filepath.Join(root, "generated", "ignored.go"), "package ignored\n")
	writeFixture(t, filepath.Join(root, "generated", "keep.go"), "package keep\n")
	writeFixture(t, filepath.Join(root, "private.go"), "package private\n")
	writeFixture(t, filepath.Join(root, "src", ".gitignore"), "*.go\n!keep.go\n")
	writeFixture(t, filepath.Join(root, "src", "ignored.go"), "package ignored\n")
	writeFixture(t, filepath.Join(root, "src", "keep.go"), "package keep\n")

	result, err := DiscoverContext(
		context.Background(),
		[]string{root},
		Options{IgnoreFiles: true},
	)
	if err != nil {
		t.Fatalf("DiscoverContext: %v", err)
	}
	if len(result.Files) != 2 {
		t.Fatalf("files = %#v, want two re-included files", result.Files)
	}
	for _, file := range result.Files {
		if !strings.HasSuffix(file.DisplayPath, "keep.go") {
			t.Fatalf("unexpected discovered file %q", file.DisplayPath)
		}
	}
	if len(result.IgnoreFiles) != 3 {
		t.Fatalf("ignore files = %#v, want root git/mori and nested git", result.IgnoreFiles)
	}
	if len(result.IgnoreEvidence) != 3 {
		t.Fatalf("ignore evidence = %#v, want three digests", result.IgnoreEvidence)
	}
	for index, evidence := range result.IgnoreEvidence {
		if evidence.Path != result.IgnoreFiles[index] || len(evidence.Digest) != 64 {
			t.Fatalf("ignore evidence %d = %#v", index, evidence)
		}
	}
}

func TestDiscoverIgnoreRulesDoNotHideExplicitFile(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	ignored := filepath.Join(root, "ignored.go")
	writeFixture(t, filepath.Join(root, ".gitignore"), "ignored.go\n")
	writeFixture(t, ignored, "package ignored\n")

	result, err := DiscoverContext(
		context.Background(),
		[]string{ignored},
		Options{IgnoreFiles: true},
	)
	if err != nil {
		t.Fatalf("DiscoverContext: %v", err)
	}
	if len(result.Files) != 1 || result.Files[0].Path != ignored {
		t.Fatalf("explicit ignored file result = %#v", result)
	}
}

func TestDiscoverRejectsInvalidIgnorePattern(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	writeFixture(t, filepath.Join(root, ".moriignore"), "[\n")
	writeFixture(t, filepath.Join(root, "main.go"), "package main\n")
	_, err := DiscoverContext(
		context.Background(),
		[]string{root},
		Options{IgnoreFiles: true},
	)
	if err == nil || !strings.Contains(err.Error(), "invalid ignore pattern") {
		t.Fatalf("DiscoverContext error = %v, want invalid ignore pattern", err)
	}
}

func writeFixture(t *testing.T, path string, content string) {
	t.Helper()
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("MkdirAll: %v", err)
	}
	if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}
}
